#!/usr/bin/env bash
# script that transfers a file from our client to a server:
# Accepts four parameters
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    PATH_TO_FILE="$1"
    IP="$2"
    USERNAME="$3"
    SSH_KEY="$4"

    scp_options="-o StrictHostKeyChecking=no -i $SSH_KEY"
    destination="$USERNAME@$IP:~/"

    scp $scp_options $PATH_TO_FILE $destination
fi
