#!/usr/bin/env bash
# Installing and configuring HAproxy on your lb-01 server.

sudo apt-get update -y
sudo apt-get upgrade -y

# Install HAProxy
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get update -y
sudo apt-get -y install haproxy=2.6.\*

# Configuration of HAProxy config file
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}

echo '
defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000

frontend haproxy-main
        bind *:80
        default_backend nginx-webservers

backend nginx-webservers
        balance roundrobin
        server 198483-web-01 54.237.217.75:80 check
        server 198483-web-02 34.224.95.2:80 check

listen stats
        bind :8800
        stats enable
        stats uri /
        stats hide-version
        stats auth myhosting:dieldogdaladanidwari
        default_backend nginx-webservers
' | sudo tee /etc/haproxy/haproxy.cfg >/dev/null


# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart
