#!/usr/bin/env bash
# A script that configures an Ubuntu server: change IP address

cp /etc/hosts ~/changed_host
echo "127.0.0.2		localhost" > ~/changed_host
echo "8.8.8.8		facebook.com" >> ~/changed_host
cp -f ~/changed_host /etc/hosts
